# Site settings
title: SaaS Masterclass
logo: "/img/CM-logo.png"
email: support@chartmogul.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "localhost:4000" # the base hostname & protocol for your site
twitter_username: ChartMogul
github_username:  projectfreedom

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page/:num"

tag_page_layout: tag_page
tag_page_dir: tag